# Generated by Django 4.0.4 on 2022-06-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_guestemail_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
