# Generated by Django 4.0.4 on 2022-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meet',
            field=models.CharField(choices=[('G-Meet', 'G-Meet'), ('Ms-Teams', 'Ms-Teams'), ('Offline', 'Offline'), ('Zoom', 'Zoom')], max_length=500, null=True),
        ),
    ]
