# Generated by Django 4.0.4 on 2022-06-16 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='authUser',
        ),
    ]
