# Generated by Django 4.0.4 on 2022-06-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='email',
        ),
        migrations.AddField(
            model_name='authuser',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
